
// Crear una nueva task.
POST http://localhost:3050/api/tasks
content-type: application/json

{
    "description": "Descripcion 2",
    "done": false,
    "location": {
        "lat": 3.17,
        "lon": 7.20
    }
}

###

// Obtener todas las task.
GET http://localhost:3050/api/tasks

###

// Obtener una task por ID.
GET http://localhost:3050/api/tasks/616d99482aca4d4599cb2449

###

// Actualizar una task.
PUT http://localhost:3050/api/tasks/616d99482aca4d4599cb2449
content-type: application/json

{
    "description": "Descripcion nueva",
    "done": false,
    "location": {
        "lat": 3.17,
        "lon": 7.20
    }
}

###

// Borrar una task.
DELETE http://localhost:3050/api/tasks/616d9acb89c587b18ab53e08