
// Crear una nueva task.
POST http://localhost:3050/api/tasks
content-type: application/json

{
    "description": "Descripcion",
    "done": false,
    "location": {
        "lat": 3.17,
        "lon": 7.20
    }
}

###

// Obtener todas las task.
GET http://localhost:3050/api/tasks

###

// Obtener una task por ID.
GET http://localhost:3050/api/tasks/616f36348053f9bdaed780a9

###

// Actualizar una task.
PUT http://localhost:3050/api/tasks/616f36348053f9bdaed780a9
content-type: application/json

{
    "description": "Descripcion nueva",
    "done": false,
    "location": {
        "lat": 3.17,
        "lon": 7.20
    }
}

###

// Borrar una task.
DELETE http://localhost:3050/api/tasks/616f368b6386f9fc2ba8e825